name: CI - Android
description: Test Running Build Kivy

inputs:
  buildozer_cmd:
    description: 'command to execute'
    required: true
    default: buildozer -v android debug

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libunwind-dev \
          zlib1g-dev
        sudo apt-get install -y \
          libsqlite3-dev \
          sqlite3 \
          bzip2 \
          libbz2-dev \
          zlib1g-dev \
          openssl \
          libgdbm-dev \
          libgdbm-compat-dev \
          liblzma-dev \
          libreadline-dev \
          uuid-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good
        sudo apt-get install -y \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          automake
    # Set up Java 17 required by Gradle
    - name: Setup Java 17 required by Gradle
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  # or 'zulu', 'liberica', etc.
        java-version: '17'

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' #set your python version

    # Install pip dependencies
    - name: Install pip dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33
        

    # Build with Buildozer
    - name: Build with Buildozer
      id: buildozer
      shell: bash
      run: |
        ${{inputs.buildozer_cmd}}
      
    # Upload artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          bin/*.apk
          bin/*.aab
